### ISSUE TITLE
Key Error u'Images' 

### ISSUE THREAD

**Issue by ghost** [saebyn/django-classifieds#2]
Hi,

I set up the app and dependencies, then added a category, image formats, and image upload fields to the category in the admin section. However, the image field is not showing up in template (classifieds/templates/classifieds/edit.html), so that when the form is submitted, there is an error:

> KeyError at /classifieds/create/edit/17/
> u'Images'
> Django Version:    1.3.1
> Exception Type:    KeyError
> Exception Value:   u'Images'
> Python Version:    2.7.3

I haven't changed anything in the template, models, or views.

The template code is the same as in the example:

```
  <tr>
    <td colspan="4">{{ imagesformset.non_form_errors }}</td>
  </tr>
     {% if imagesformset.forms %}
  <tr>
  <td colspan="4">
     <h3 style="font-size: 16px;">Add Picture(s)</h3>
  </td>
  </tr>
  <tr>
  <td colspan="4">Uploaded images must be smaller than {{ ad.category.images_max_size|filesizeformat }}. Images with dimensions larger than {{ ad.category.images_max_width }} by {{ ad.category.images_max_height }} pixels will be resized.
   Images must be in one of the following formats:
       {% for format in ad.category.images_allowed_formats.all %}
   {{ format.format }}

.................etc................
```

Am I missing something that is preventing the image form from being included in the template?

**Comment by saebyn** [comment]
That field type isn't implemented yet, but you should be able to have images for ads by setting the "Images max count" on the category to a value greater than 0.

**Comment by ghost** [comment]
Thank you.
